# Tranquilpeak
# Version : 0.3.1-BETA
# Author : Thibaud LeprÃªtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseURL = "http://nianze.tk"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "To be creative"
theme = "tranquilpeak"
googleAnalytics = "UA-71584380-1"
paginate = 6
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "åˆ€å¿ƒã®æ°´"
  bio = "è™šåº¦å»¿ä½™å²æœˆæµ…ï¼Œç•¥è¯†å‡ è¡Œä»£ç æºã€‚\t\né—²æ¥éšæ‰‹å¿«é—¨æŒ‰ï¼Œé»¯ç„¶ç‹¬æŠŠéŸ³éŸµå¼¹ã€‚\n\nPain is inevitable. \t\nSuffering is optional."
  job = "Developer"
  location = "New York"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  # gravatarEmail = "daoxinzhishui@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "/images/cut.PNG"
  # Your Twitter username without the @. E.g : thibaudlepretre
  # twitter = "daoxinzhishui"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  # googlePlus = "+ThibaudLepretre"

# Menu Configuration
[[menu.main]]
  weight = 1 
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-home\" title='Home'></i>"
  url = "/"
[[menu.main]]
  weight = 1 
  identifier = "thoughts"
  name = "Thoughts"
  pre = "<i class=\"sidebar-button-icon fas fa-lightbulb\" title='Thoughts'></i>"
  url = "/categories/thoughts"
[[menu.main]]
  weight = 2 
  identifier = "technology"
  name = "Technology"
  pre = "<i class=\"sidebar-button-icon fas fa-code\" title='Technology'></i>"
  url = "/categories/technology"
[[menu.main]]
  weight = 3 
  identifier = "music"
  name = "Music"
  pre = "<i class=\"sidebar-button-icon fas fa-music\" title='Music'></i>"
  url = "/categories/music"
[[menu.main]]
  weight = 4 
  identifier = "visual"
  name = "Visual"
  pre = "<i class=\"sidebar-button-icon fas fa-palette\" title='Visual'></i>"
  url = "/categories/visual"
[[menu.main]]
  weight = 5
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fas fa-bookmark\" title='Categories'></i>"
  url = "/categories"
[[menu.main]]
  weight = 6
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fas fa-tags\" title='Tags'></i>"
  url = "/tags"
[[menu.main]]
  weight = 7
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fas fa-archive\" title='Archives'></i>"
  url = "/archives"
[[menu.main]]
  weight = 8
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fas fa-user\" title='About'></i>"
  url = "/about"

[[menu.links]]
  weight = 1
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "<i class=\"sidebar-button-icon fab fa-linkedin\" title='LinkedIn'></i>"
  url = "https://www.linkedin.com/in/nianze"
[[menu.links]]
  weight = 2
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-github\" title='Github'></i>"
  url = "https://github.com/Nianze"
[[menu.links]]
  weight = 3
  identifier = "flickr"
  name = "Flickr"
  pre = "<i class=\"sidebar-button-icon fab fa-flickr\", title='Flickr'></i>"
  url = "https://www.flickr.com/photos/129774362@N07/"
[[menu.links]]
  weight = 4
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class=\"sidebar-button-icon fab fa-instagram\" title='Instagram'></i>"
  url = "https://instagram.com/eznain"
[[menu.links]]
  weight = 5
  identifier = "facebook"
  name = "Facebook"
  pre = "<i class=\"sidebar-button-icon fab fa-facebook\", title='Facebook'></i>"
  url = "https://www.facebook.com/rym.lnz"
[[menu.links]]
 weight = 6
 identifier = "twitter"
 name = "Twitter"
 pre = "<i class=\"sidebar-button-icon fab fa-twitter\", title='Twitter'></i>"
 url = "https://twitter.com/daoxinzhishui"
[[menu.links]]
  weight = 8
  identifier = "weibo"
  name = "Weibo"
  pre = "<i class=\"sidebar-button-icon fab fa-weibo\", title='Weibo'></i>"
  url = "http://weibo.com/daoxinzhishui" 
[[menu.links]]
  weight = 7
  identifier = "youtube"
  name = "YouTube"
  pre = "<i class=\"sidebar-button-icon fab fa-youtube\", title='YouTube'></i>"
  url = "https://www.youtube.com/user/daoxinzhishui"
[[menu.links]]
  weight = 9
  identifier = "email"
  name = "Email"
  pre = "<i class=\"sidebar-button-icon fas fa-envelope\", title='Email'></i>"
  url = "mailto:daoxinzhishui@gmail.com"

[params]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  # dateFormat = "2 January 2006"

  # Global keywords configuration. Following keywords will be add to every pages
  keywords = ["visual", "music", "technology"]

  # Syntax highlighter, possible choice between: "highlight.js" (recommanded) and "prism.js" (experimental)
  # You can comment it to disable syntax highlighting
  syntaxHighlighter = "highlight.js"

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  description = "åˆ€å¿ƒæ°´å‘å‘†ã®åœ°æ–¹"

  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 1

  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image in folder `static/_images/` (development)  or in `source/assets/images/` if you can't or don't want to build the theme,
  # and use relative url : `your-image.png`
  coverImage = "/city_silhouette.jpg"

  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true
  # Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
  # Set this value to `right` if you have old posts to keep the old style on them
  # and define `thumbnailImagePosition` on a post to overwrite this setting
  thumbnailImagePosition = "right"
  # Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
  # Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image

  # and set `autoThumbnailImage` to `false` on a post to overwrite this setting
  autoThumbnailImage = false

  # Your favicon path, default is "/favicon.png"
  favicon = "/favicon.png"

  # Header configuration
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  #     url: /#search
  #     icon: search
  #     class: st-search-show-outputs

  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
  # [[params.customCSS]]
  #   href = "css/mystyle.css"
  customCSS = ["css/main.css", "css/loader.css"]

  # Custom JS. Put here your custom JS files. They are loaded after the theme JS;
  # they have to be referred from static root. Example
  # [[params.customJS]]
  #   src = "js/myscript.js"
  customJS = ["js/loader.js"]

  # Display `Next` on left side of the pagination, and `Prev` on right side one.
  # If you set this value to `true`, these positions swap.
  # swapPaginator = true

  # Sharing options
  # Comment and uncomment to enable or disable sharing options
  # If you wanna add a sharing option, read user documentation :
  # Tranquilpeak configuration > Theme configuration > sharing-options
  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-f"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.sharingOptions]]
    name = "Google+"
    icon = "fa-google-plus-g"
    url = "https://plus.google.com/share?url=%s"

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

  [params.utteranc] # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "Nianze/personal-site-comments"
    label = "âœ¨comment ğŸ’¬"
    issueTerm = "pathname"

  # Customize link of author avatar in sidebar
  # [params.sidebar.profile]
  #   url = "/#about"